// --- DOM要素の取得 ---
const dropZone = document.getElementById('drop-zone');
const fileInput = document.getElementById('file-input');
const statusText = document.getElementById('status-text');
const resultArea = document.getElementById('result-area');
const statusCursor = document.querySelector('.cursor');

// --- イベントリスナーの設定 ---
// (変更なし)
fileInput.addEventListener('change', (e) => {
    handleFiles(e.target.files);
});
dropZone.addEventListener('dragover', (e) => {
    e.preventDefault();
    dropZone.classList.add('drag-over');
});
dropZone.addEventListener('dragleave', (e) => {
    e.preventDefault();
    dropZone.classList.remove('drag-over');
});
dropZone.addEventListener('drop', (e) => {
    e.preventDefault();
    dropZone.classList.remove('drag-over');
    handleFiles(e.dataTransfer.files);
});

// --- メイン処理関数 ---
async function handleFiles(files) {
    resultArea.innerHTML = '';
    
    if (!files || files.length === 0) {
        updateStatus("Error: No folder selected.", true);
        return;
    }

    const projectName = files[0].webkitRelativePath.split('/')[0];
    updateStatus(`Project "${projectName}" detected. Processing...`);

    try {
        const zip = new JSZip();

        // --- 変更点 1: background.js の内容を定義 ---
        // アイコンクリック時に新しいタブで index.html を開くスクリプト
        const backgroundScriptContent = `chrome.action.onClicked.addListener((tab) => {
    chrome.tabs.create({ url: 'index.html' });
});`;
        // background.js をZIPに追加
        zip.file("background.js", backgroundScriptContent);


        // --- 変更点 2: manifest.json の内容を新しい仕様に変更 ---
        const manifest = {
            manifest_version: 3,
            name: `Anti_CORS_${projectName}`,
            version: "1.0",
            description: `Generated by Anti_CORS tool for local development of '${projectName}'.`,
            // "action" の中身を空にして、クリックイベントをbackground.jsに委ねる
            action: {},
            // バックグラウンドで動作するService Workerとしてbackground.jsを指定
            background: {
                service_worker: "background.js"
            }
        };
        // manifest.jsonを整形してZIPに追加
        zip.file("manifest.json", JSON.stringify(manifest, null, 2));


        // 2. ユーザーの全ファイルを読み込み、ZIPに追加
        // (この部分のロジックは変更なし)
        const filePromises = Array.from(files).map(file => {
            return new Promise((resolve, reject) => {
                const pathInZip = file.webkitRelativePath.substring(projectName.length + 1);
                if (pathInZip) {
                    const reader = new FileReader();
                    reader.onload = (e) => {
                        zip.file(pathInZip, e.target.result);
                        resolve();
                    };
                    reader.onerror = reject;
                    reader.readAsArrayBuffer(file);
                } else {
                    resolve();
                }
            });
        });
        
        await Promise.all(filePromises);

        updateStatus("Generating ZIP package...");

        // 3. ZIPファイルを生成
        const blob = await zip.generateAsync({ type: "blob" });

        // 4. ダウンロードリンクを生成
        createDownloadLink(blob, projectName);
        updateStatus("Complete! Package is ready for download.", false);

    } catch (error) {
        console.error("An error occurred:", error);
        updateStatus(`Error: ${error.message}`, true);
    }
}

// --- ヘルパー関数 ---
// (変更なし)
function updateStatus(message, isError = false) {
    statusText.textContent = message;
    statusText.style.color = isError ? 'var(--accent-color)' : 'var(--text-color)';
    statusCursor.style.display = (message.endsWith('...') || message.includes('Awaiting')) ? 'inline-block' : 'none';
}

function createDownloadLink(blob, projectName) {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    const timestamp = new Date().toISOString().replace(/[-:.]/g, '').slice(0, 14);
    const filename = `Anti_CORS_${projectName}_${timestamp}.zip`;
    a.href = url;
    a.download = filename;
    a.textContent = `DOWNLOAD: ${filename}`;
    a.addEventListener('click', () => {
        setTimeout(() => URL.revokeObjectURL(url), 100);
    });
    resultArea.appendChild(a);
}